version: "3"

services:
  php:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
  mysql:
    platform: linux/x86_64
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_app
      MYSQL_USER: my_app
      MYSQL_PASSWORD: secret
      TZ: "Asia/Tokyo"
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  db-data:
